version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    #MONGO_INITDB_ROOT_USERNAME: nikita
    #MONGO_INITDB_ROOT_PASSWORD: secret
    #- MONGO_INITDB_ROOT_USERNAME=nikita
    #- MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./back
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./back:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
